apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - vault-network-policy.yaml
  - argocd-network-policy.yaml
  - grafana-network-policy.yaml
  - postgresql-network-policy.yaml
  - qdrant-network-policy.yaml
