#!/usr/bin/env bun

import Parser from 'rss-parser'
import { prisma } from '../src/lib/prisma'
import { createCollection } from '../src/lib/collections/service'

const parser = new Parser({
  customFields: {
    item: [
      ['dc:creator', 'creator'],
      ['dc:subject', 'subject'],
      ['dc:date', 'dcDate'],
      ['content:encoded', 'contentEncoded'],
    ],
  },
})

// Sample JUPORTAL RSS feed URLs with search parameters
// These URLs are generated by JUPORTAL when you save a search as RSS flux
const JUPORTAL_RSS_FEEDS = {
  // Example: Search for "paulienne" in all texts
  paulienne:
    'https://juportal.be/moteur/Flux-RSS.rss?eNqFVMlu2zAQ/ZVA1yCAliiLfKJJ2qIzJgUuSHMKfMihQOEEKHoK8u8dSlZNiqVzk/geOcubeYeubbrP313VdgXVwlr+Y9DcGKFkscLjqiuurj8Of379fDse38aj2xNTc9oj3XJ/WnfF+3GEHwKYUxBW4KdHyq4YCfcBYa8ocBDr+Ik2YGAybr8I0QS4VMsEwtuDW4OgYfQQBSK3EvK3Pb7Rl3GWrW0jODAgz8XqgPjnF75SLnvzMnDGaYaxc8Zy2Dkt2JkRhTAcU5CcB/DjIoTE7mmVy9EzqHI6xJcCniLkCUqzSOGkTMIYJvKUk0EqrSCKEBaB/RF+HFk2h5lBck9MU0Bs/omZQXKNsj03lJgq6PRDCmeF8riz7tJ1hKPrYQFrgkrzLQGeGZUTgRGb7eOJgvPwDYNoGzKaaF2nFmJpa4WaEZlQ1MDHacIzIlliGIaqaVbQWMoEBbEXY3Acj7otyzKdlWEg23nh2wm/i2oAUJN3zQWEcC9AbHsbr3TYA9Or5/9ZzpKDiqHe33JQ1MucvbKJ/S05qAvKklPNMzYCF83MbQdIGosrOsmCvTxLcBctkR/g0Srxov+bV3kjABmvfpWfzn7xbwyblDHamgptrUpJC+NaRkrdM7FeN2s0eXRVR54yjnmNndq5QWlL/OlrXdbtTVXdVI/4WdbNfbH6+gu5YOOR',

  // You can add more specific searches here as needed
  // The encoded parameter contains the search criteria and filters
}

interface JurisprudenceItem {
  title: string
  link: string
  pubDate: string
  description: string
  guid: string
  creator?: string
  subject?: string
  dcDate?: string
  contentEncoded?: string
  ecli?: string
}

async function fetchRSSFeed(feedUrl: string): Promise<JurisprudenceItem[]> {
  try {
    console.log(`Fetching RSS feed: ${feedUrl}`)
    const feed = await parser.parseURL(feedUrl)

    console.log(`Found ${feed.items.length} items in feed: ${feed.title}`)

    return feed.items.map((item) => ({
      title: item.title || '',
      link: item.link || '',
      pubDate: item.pubDate || '',
      description:
        (item as unknown as { description?: string }).description || '',
      guid: item.guid || '',
      creator: item.creator,
      subject: item.subject,
      dcDate: item.dcDate,
      contentEncoded: item.contentEncoded,
      ecli: extractECLI(
        item.title ||
          (item as unknown as { description?: string }).description ||
          ''
      ),
    }))
  } catch (error) {
    console.error(`Error fetching RSS feed ${feedUrl}:`, error)
    return []
  }
}

function extractECLI(text: string): string | undefined {
  const ecliPattern = /ECLI:[A-Z]{2}:[A-Z]+:\d{4}:[A-Z0-9.]+/
  const match = text.match(ecliPattern)
  return match ? match[0] : undefined
}

async function fetchAllJUPORTALFeeds() {
  console.log('Starting JUPORTAL RSS fetch...\n')

  // Get the first user from the database
  const user = await prisma.user.findFirst()

  if (!user) {
    throw new Error('No users found in database. Please create a user first.')
  }

  const userId = user.id
  console.log(`Using user: ${user.email} (${userId})\n`)

  // Find or create collection
  let collection = await prisma.collection.findFirst({
    where: {
      name: 'JUPORTAL Jurisprudence RSS',
      ownerId: userId,
    },
  })

  if (!collection) {
    console.log('Creating JUPORTAL RSS collection...')
    collection = await createCollection({
      name: 'JUPORTAL Jurisprudence RSS',
      description: 'Belgian case law from JUPORTAL RSS feeds',
      visibility: 'PRIVATE',
      ownerId: userId,
      embeddingModel: 'text-embedding-3-small',
      chunkSize: 1000,
      chunkOverlap: 200,
    })
  }

  console.log(`Using collection: ${collection.name} (${collection.id})\n`)

  const allDocuments: JurisprudenceItem[] = []

  // Fetch from each RSS feed
  for (const [courtName, feedUrl] of Object.entries(JUPORTAL_RSS_FEEDS)) {
    console.log(`\nFetching ${courtName} feed...`)
    const documents = await fetchRSSFeed(feedUrl)
    allDocuments.push(...documents)

    // Store documents in database
    for (const doc of documents) {
      try {
        // Check if document already exists by filename
        const filename = `${doc.ecli || doc.guid}.html`
        const existingDoc = await prisma.document.findFirst({
          where: {
            collectionId: collection.id,
            filename: filename,
          },
        })

        if (!existingDoc) {
          await prisma.document.create({
            data: {
              filename: filename,
              originalName: filename,
              mimeType: 'text/html',
              fileSize: BigInt((doc.contentEncoded || doc.description).length),
              fileUrl: doc.link,
              collectionId: collection.id,
              uploadedById: userId,
              title: doc.title || doc.ecli || 'Untitled',
              status: 'PENDING',
              extractedText: doc.contentEncoded || doc.description,
            },
          })

          console.log(`  Added: ${doc.title}`)
        } else {
          console.log(`  Skipped (exists): ${doc.title}`)
        }
      } catch (error) {
        console.error(`  Error adding document: ${error}`)
      }
    }

    // Add delay between feeds to be respectful
    await new Promise((resolve) => setTimeout(resolve, 2000))
  }

  console.log(`\n✅ Fetched ${allDocuments.length} documents total`)
  console.log('\nSummary by court:')

  const summary: Record<string, number> = {}
  for (const [courtName, feedUrl] of Object.entries(JUPORTAL_RSS_FEEDS)) {
    const count = allDocuments.filter((doc) =>
      doc.link?.includes(feedUrl.split('/').pop() || '')
    ).length
    if (count > 0) {
      summary[courtName] = count
      console.log(`  ${courtName}: ${count} documents`)
    }
  }

  return allDocuments
}

// Execute if run directly
if (require.main === module) {
  fetchAllJUPORTALFeeds()
    .then(() => {
      console.log('\nDone!')
      process.exit(0)
    })
    .catch((error) => {
      console.error('Fatal error:', error)
      process.exit(1)
    })
}

export { fetchAllJUPORTALFeeds, fetchRSSFeed, JUPORTAL_RSS_FEEDS }
