---
# ExternalDNS Application
# Automatically manages DNS records in Cloudflare for Kubernetes resources

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: external-dns
    repoURL: https://kubernetes-sigs.github.io/external-dns/
    targetRevision: 1.14.0
    helm:
      releaseName: external-dns
      values: |
        provider: cloudflare
        cloudflare:
          secretName: cloudflare-api-token
          proxied: true
        policy: sync
        sources:
          - service
          - ingress
        domainFilters:
          - huberty.pro
          - docuralis.com
        txtOwnerId: k3s-cluster
        logLevel: info
        interval: 1m
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 2m
