---
# yamllint configuration
extends: default

rules:
  # Allow longer lines
  line-length:
    max: 120
    level: warning

  # Allow multiple documents in a single file (common in Kubernetes)
  document-start: disable

  # Allow truthy values (yes/no, on/off, etc.)
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no', 'on', 'off']
    check-keys: false

  # Indentation (2 spaces)
  indentation:
    spaces: 2
    indent-sequences: true

  # Comments
  comments:
    min-spaces-from-content: 1

  # Brackets and braces
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1

  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1

  # Empty values
  empty-values:
    forbid-in-block-mappings: false
    forbid-in-flow-mappings: true
