apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
    component: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        component: api
    spec:
      containers:
        - name: backend
          image: ghcr.io/nicolashuberty/k3s-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: HOST
              value: "0.0.0.0"
            - name: PORT
              value: "8080"
            - name: RUST_LOG
              value: "info"
            - name: DATABASE_URL
              value: "postgresql://rag_admin:changeme123@postgresql.database:5432/rag_database"
            - name: MINIO_ENDPOINT
              value: "minio.storage:9000"
            - name: MINIO_ACCESS_KEY
              value: "minioadmin"
            - name: MINIO_SECRET_KEY
              value: "minioadmin123"
            - name: QDRANT_URL
              value: "http://qdrant.database:6334"
            - name: VAULT_ADDR
              value: "http://vault.vault:8200"
            - name: VAULT_TOKEN
              value: "root"
            - name: JWT_SECRET
              value: "your-super-secret-jwt-key-change-in-production"
            - name: MINIO_BUCKET
              value: "rag-files"
            - name: REDIS_URL
              value: "redis://redis:6379"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
