apiVersion: v1
kind: Service
metadata:
  name: docuralis
  labels:
    app: docuralis
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: docuralis
