apiVersion: apps/v1
kind: Deployment
metadata:
  name: memo
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: frontend
          image: ghcr.io/nicolashuberty/full-stack-k3s/memo-app:latest
          env:
            - name: NEXTAUTH_URL
              value: "https://staging.memo.docuralis.com"
            - name: NEXT_PUBLIC_APP_URL
              value: "https://staging.memo.docuralis.com"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memo-worker
spec:
  replicas: 1
