apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base/backend
  - ../../base/frontend
  - ../../base/redis
  - ingress.yaml

namePrefix: dev-

commonLabels:
  environment: dev
  managed-by: argocd

images:
  - name: ghcr.io/nicolashuberty/k3s-backend
    newTag: dev
  - name: ghcr.io/nicolashuberty/k3s-frontend
    newTag: dev

patches:
  - target:
      kind: Deployment
      name: backend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/env/13/value
        value: "redis://dev-redis:6379"
  - target:
      kind: Deployment
      name: frontend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1

configMapGenerator:
  - name: env-config
    literals:
      - ENVIRONMENT=dev
      - LOG_LEVEL=debug
