apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base/docuralis
  - docuralis-ingress.yaml

patchesStrategicMerge:
  - docuralis-patch.yaml

namePrefix: dev-

commonLabels:
  environment: dev
  managed-by: argocd

images:
  - name: ghcr.io/nicolashuberty/k3s-app/docuralis
    newTag: dev

configMapGenerator:
  - name: env-config
    literals:
      - ENVIRONMENT=dev
      - LOG_LEVEL=debug
