---
# ClusterSecretStore for Vault
# Note: The vault-token secret must be created manually:
# kubectl create secret generic vault-token -n external-secrets --from-literal=token=YOUR_VAULT_TOKEN
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-secret-store
spec:
  provider:
    vault:
      server: "https://vault.huberty.pro"
      path: "secret"
      version: "v2"
      auth:
        tokenSecretRef:
          name: vault-token
          namespace: external-secrets
          key: token
