apiVersion: apps/v1
kind: Deployment
metadata:
  name: docuralis
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: docuralis
          image: ghcr.io/nicolashuberty/k3s-app/docuralis:staging
          env:
            - name: NEXTAUTH_URL
              value: "https://staging.docuralis.com"
