apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - ../../base/docuralis
  - docuralis-ingress.yaml

patchesStrategicMerge:
  - docuralis-patch.yaml

namePrefix: staging-

commonLabels:
  environment: staging
  managed-by: argocd

images:
  - name: ghcr.io/nicolashuberty/k3s-app/docuralis
    newTag: staging

configMapGenerator:
  - name: env-config
    literals:
      - ENVIRONMENT=staging
      - LOG_LEVEL=info
