apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - ../../base/backend
  - ../../base/frontend
  - ingress.yaml

namePrefix: staging-

commonLabels:
  environment: staging
  managed-by: argocd

images:
  - name: ghcr.io/nicolashuberty/k3s-backend
    newTag: staging
  - name: ghcr.io/nicolashuberty/k3s-frontend
    newTag: staging

patches:
  - target:
      kind: Deployment
      name: backend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
  - target:
      kind: Deployment
      name: frontend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2

configMapGenerator:
  - name: env-config
    literals:
      - ENVIRONMENT=staging
      - LOG_LEVEL=info
