apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bastion
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/NicolasHuberty/full-stack-k3s.git
    targetRevision: main
    path: infra/base/bastion
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
