apiVersion: v1
kind: Service
metadata:
  name: bastion
  labels:
    app: bastion
spec:
  selector:
    app: bastion
  ports:
    - name: ssh
      port: 22
      targetPort: 22
      protocol: TCP
  type: ClusterIP
