---
# ExternalSecret for Dev Environment
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: docuralis-secrets
  namespace: dev
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: docuralis-secrets
    creationPolicy: Owner
  data:
    # Database
    - secretKey: database-url
      remoteRef:
        key: secret/data/docuralis/dev
        property: database_url

    # NextAuth
    - secretKey: nextauth-secret
      remoteRef:
        key: secret/data/docuralis/dev
        property: nextauth_secret

    # OAuth - Google
    - secretKey: google-client-id
      remoteRef:
        key: secret/data/docuralis/oauth
        property: google_client_id

    - secretKey: google-client-secret
      remoteRef:
        key: secret/data/docuralis/oauth
        property: google_client_secret

    # OAuth - GitHub
    - secretKey: github-client-id
      remoteRef:
        key: secret/data/docuralis/oauth
        property: github_client_id

    - secretKey: github-client-secret
      remoteRef:
        key: secret/data/docuralis/oauth
        property: github_client_secret

    # OAuth - Azure AD
    - secretKey: azure-ad-client-id
      remoteRef:
        key: secret/data/docuralis/oauth
        property: azure_ad_client_id

    - secretKey: azure-ad-client-secret
      remoteRef:
        key: secret/data/docuralis/oauth
        property: azure_ad_client_secret

    - secretKey: azure-ad-tenant-id
      remoteRef:
        key: secret/data/docuralis/oauth
        property: azure_ad_tenant_id

    # MinIO
    - secretKey: minio-endpoint
      remoteRef:
        key: secret/data/infrastructure/minio
        property: endpoint

    - secretKey: minio-access-key
      remoteRef:
        key: secret/data/infrastructure/minio
        property: access_key

    - secretKey: minio-secret-key
      remoteRef:
        key: secret/data/infrastructure/minio
        property: secret_key

    # Qdrant
    - secretKey: qdrant-url
      remoteRef:
        key: secret/data/infrastructure/qdrant
        property: url

    - secretKey: qdrant-api-key
      remoteRef:
        key: secret/data/infrastructure/qdrant
        property: api_key

    # OpenAI
    - secretKey: openai-api-key
      remoteRef:
        key: secret/data/docuralis/api-keys
        property: openai_api_key

    # SMTP (optional)
    - secretKey: smtp-host
      remoteRef:
        key: secret/data/docuralis/smtp
        property: smtp_host

    - secretKey: smtp-port
      remoteRef:
        key: secret/data/docuralis/smtp
        property: smtp_port

    - secretKey: smtp-user
      remoteRef:
        key: secret/data/docuralis/smtp
        property: smtp_user

    - secretKey: smtp-password
      remoteRef:
        key: secret/data/docuralis/smtp
        property: smtp_password

    - secretKey: smtp-from
      remoteRef:
        key: secret/data/docuralis/smtp
        property: smtp_from

---
# ExternalSecret for Staging Environment
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: docuralis-secrets
  namespace: staging
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: docuralis-secrets
    creationPolicy: Owner
  data:
    # Database
    - secretKey: database-url
      remoteRef:
        key: secret/data/docuralis/staging
        property: database_url

    # NextAuth
    - secretKey: nextauth-secret
      remoteRef:
        key: secret/data/docuralis/staging
        property: nextauth_secret

    # OAuth - Google
    - secretKey: google-client-id
      remoteRef:
        key: secret/data/docuralis/oauth
        property: google_client_id

    - secretKey: google-client-secret
      remoteRef:
        key: secret/data/docuralis/oauth
        property: google_client_secret

    # OAuth - GitHub
    - secretKey: github-client-id
      remoteRef:
        key: secret/data/docuralis/oauth
        property: github_client_id

    - secretKey: github-client-secret
      remoteRef:
        key: secret/data/docuralis/oauth
        property: github_client_secret

    # OAuth - Azure AD
    - secretKey: azure-ad-client-id
      remoteRef:
        key: secret/data/docuralis/oauth
        property: azure_ad_client_id

    - secretKey: azure-ad-client-secret
      remoteRef:
        key: secret/data/docuralis/oauth
        property: azure_ad_client_secret

    - secretKey: azure-ad-tenant-id
      remoteRef:
        key: secret/data/docuralis/oauth
        property: azure_ad_tenant_id

    # MinIO
    - secretKey: minio-endpoint
      remoteRef:
        key: secret/data/infrastructure/minio
        property: endpoint

    - secretKey: minio-access-key
      remoteRef:
        key: secret/data/infrastructure/minio
        property: access_key

    - secretKey: minio-secret-key
      remoteRef:
        key: secret/data/infrastructure/minio
        property: secret_key

    # Qdrant
    - secretKey: qdrant-url
      remoteRef:
        key: secret/data/infrastructure/qdrant
        property: url

    - secretKey: qdrant-api-key
      remoteRef:
        key: secret/data/infrastructure/qdrant
        property: api_key

    # OpenAI
    - secretKey: openai-api-key
      remoteRef:
        key: secret/data/docuralis/api-keys
        property: openai_api_key

    # SMTP (optional)
    - secretKey: smtp-host
      remoteRef:
        key: secret/data/docuralis/smtp
        property: smtp_host

    - secretKey: smtp-port
      remoteRef:
        key: secret/data/docuralis/smtp
        property: smtp_port

    - secretKey: smtp-user
      remoteRef:
        key: secret/data/docuralis/smtp
        property: smtp_user

    - secretKey: smtp-password
      remoteRef:
        key: secret/data/docuralis/smtp
        property: smtp_password

    - secretKey: smtp-from
      remoteRef:
        key: secret/data/docuralis/smtp
        property: smtp_from

---
# ExternalSecret for Production Environment
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: docuralis-secrets
  namespace: production
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: docuralis-secrets
    creationPolicy: Owner
  data:
    # Database
    - secretKey: database-url
      remoteRef:
        key: secret/data/docuralis/production
        property: database_url

    # NextAuth
    - secretKey: nextauth-secret
      remoteRef:
        key: secret/data/docuralis/production
        property: nextauth_secret

    # OAuth - Google
    - secretKey: google-client-id
      remoteRef:
        key: secret/data/docuralis/oauth
        property: google_client_id

    - secretKey: google-client-secret
      remoteRef:
        key: secret/data/docuralis/oauth
        property: google_client_secret

    # OAuth - GitHub
    - secretKey: github-client-id
      remoteRef:
        key: secret/data/docuralis/oauth
        property: github_client_id

    - secretKey: github-client-secret
      remoteRef:
        key: secret/data/docuralis/oauth
        property: github_client_secret

    # OAuth - Azure AD
    - secretKey: azure-ad-client-id
      remoteRef:
        key: secret/data/docuralis/oauth
        property: azure_ad_client_id

    - secretKey: azure-ad-client-secret
      remoteRef:
        key: secret/data/docuralis/oauth
        property: azure_ad_client_secret

    - secretKey: azure-ad-tenant-id
      remoteRef:
        key: secret/data/docuralis/oauth
        property: azure_ad_tenant_id

    # MinIO
    - secretKey: minio-endpoint
      remoteRef:
        key: secret/data/infrastructure/minio
        property: endpoint

    - secretKey: minio-access-key
      remoteRef:
        key: secret/data/infrastructure/minio
        property: access_key

    - secretKey: minio-secret-key
      remoteRef:
        key: secret/data/infrastructure/minio
        property: secret_key

    # Qdrant
    - secretKey: qdrant-url
      remoteRef:
        key: secret/data/infrastructure/qdrant
        property: url

    - secretKey: qdrant-api-key
      remoteRef:
        key: secret/data/infrastructure/qdrant
        property: api_key

    # OpenAI
    - secretKey: openai-api-key
      remoteRef:
        key: secret/data/docuralis/api-keys
        property: openai_api_key

    # SMTP
    - secretKey: smtp-host
      remoteRef:
        key: secret/data/docuralis/smtp
        property: smtp_host

    - secretKey: smtp-port
      remoteRef:
        key: secret/data/docuralis/smtp
        property: smtp_port

    - secretKey: smtp-user
      remoteRef:
        key: secret/data/docuralis/smtp
        property: smtp_user

    - secretKey: smtp-password
      remoteRef:
        key: secret/data/docuralis/smtp
        property: smtp_password

    - secretKey: smtp-from
      remoteRef:
        key: secret/data/docuralis/smtp
        property: smtp_from
