apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-secret-store
spec:
  provider:
    vault:
      server: "https://vault.my-company.com"
      path: "secret"
      version: "v2"
      auth:
        tokenSecretRef:
          name: vault-token   # Kubernetes Secret containing the Vault token
          key: token
