apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: memo-app-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/nhuberty/k3s-app.git
    targetRevision: main
    path: k8s/memo-app/overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: memo-app-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
