apiVersion: apps/v1
kind: Deployment
metadata:
  name: docuralis
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: docuralis
          image: ghcr.io/nicolashuberty/k3s-app/docuralis:latest
          env:
            - name: NEXTAUTH_URL
              value: "https://app.docuralis.com"
