apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
  - ../../base/backend
  - ../../base/frontend
  - ingress.yaml

namePrefix: prod-

commonLabels:
  environment: production
  managed-by: argocd

images:
  - name: ghcr.io/nicolashuberty/k3s-backend
    newTag: latest
  - name: ghcr.io/nicolashuberty/k3s-frontend
    newTag: latest

patches:
  - target:
      kind: Deployment
      name: backend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
  - target:
      kind: Deployment
      name: frontend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3

configMapGenerator:
  - name: env-config
    literals:
      - ENVIRONMENT=production
      - LOG_LEVEL=warn
